### ISSUE TITLE
gradle build fails 

### ISSUE THREAD

**Issue by goodmike** [andrewharmellaw/first-steps-in-ddd#1]
After cloning the project, I ran `gradle build` and the following output appeared:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/michael/learning-dev/DDD-Course/first-steps-in-ddd/build.gradle' line: 13

* What went wrong:
A problem occurred evaluating root project 'first-steps-in-ddd'.
> Could not find method compile() for arguments [org.apache.commons:commons-collections4:4.4] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
```

I am not an experienced Java developer, and I have no experience with gradle, FYI.

**Comment by bruce-koho** [comment]
I'm getting the exact same issue running `gradle build`.  I'm also not experienced with Java/Gradle and am hoping to get this resolved before tomorrow's DDD online session.

I'm on OSX running Java 16.0.1 and Gradle 7.0.1.

@goodmike are you attending as well?  I'm going to try and reach out to the event organizers.

**Comment by jimtyhurst** [comment]
I had the same problem. According to [Could not find method compile() for arguments Gradle
](https://stackoverflow.com/questions/23796404/could-not-find-method-compile-for-arguments-gradle):

> Note that the `compile`, `runtime`, `testCompile`, and `testRuntime` configurations introduced by the Java plugin have been deprecated since [Gradle 4.10](https://docs.gradle.org/4.10/userguide/java_plugin.html#sec:java_plugin_and_dependency_management) ([Aug 27, 2018](https://gradle.org/releases/)), and were finally removed in [Gradle 7.0](https://docs.gradle.org/7.0/userguide/java_library_plugin.html#sec:java_library_configurations_graph) ([Apr 9, 2021](https://gradle.org/releases/)).
> 
> The aforementioned configurations should be replaced by `implementation`, `runtimeOnly`, `testImplementation`, and `testRuntimeOnly`, respectively.

So the problem might only be encountered by those of us using Gradle 7.x.

When I changed `gradle.build` line 13 from:
```
compile 'org.apache.commons:commons-collections4:4.4'
```
to:
```
implementation 'org.apache.commons:commons-collections4:4.4'
```
then `gradle build` completed successfully for me.

I am using:
```
Gradle 7.0
JVM:          11.0.7 (Oracle Corporation 11.0.7+8-LTS)
OS:           Mac OS X 10.16 x86_64
```

**Comment by bruce-koho** [comment]
Thanks for providing this workaround @jimtyhurst, this fixed it for me!

**Comment by andrewharmellaw** [comment]
Thanks @jimtyhurst (and apologies @bruce-koho and @goodmike I missed this until too late.  I hope you got something out of the training despite this.)
